<a href="https://colab.research.google.com/github/Thanatipz/BSC_DPDM23/blob/main/association_rule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
survey = pd.read_excel('/content/drive/MyDrive/BSC_DPDM23/Project_data/dataset_consumer-insight-survey2019.xlsx')

In [ ]:
survey = pd.read_excel('/content/drive/MyDrive/bsc2 2566/dataset_consumer-insight-survey2019.xlsx')

In [ ]:
survey_association = survey.copy()

In [ ]:
survey_association = survey_association[['k1', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8', 'k9', 'k10', 'r1', 'r2', 'r3', 'r4', 'r5','rr1']]

In [ ]:
survey_association['r2'] = survey_association['r2'].replace({21: 99, 80: 99})
survey_association['r3'] = survey_association['r3'].replace({31: 99})

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
survey = pd.read_excel('/content/drive/MyDrive/BSC_DPDM23/Project_data/dataset_consumer-insight-survey2019.xlsx')

In [ ]:
survey_association = survey.copy()

In [ ]:
survey_association = survey_association[['k1', 'k2', 'k3', 'k4', 'k5', 'k6', 'k7', 'k8', 'k9', 'k10', 'r1', 'r2', 'r3', 'r4', 'r5','rr1']]

In [ ]:
survey_association['r2'] = survey_association['r2'].replace({21: 99, 80: 99})
survey_association['r3'] = survey_association['r3'].replace({31: 99})

In [ ]:
survey_association['new_column'] = survey_association[['r1', 'r2', 'r3', 'r4', 'r5','rr1']].apply(list, axis=1)

In [ ]:
survey_association['for_association'] = survey_association['new_column'].apply(lambda x: [i for i in x if i != 99])

In [ ]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=079f9012b749830ad0bf17ff7f09cf361e41e2c97045414d9f303cd6560bf7fb
  Stored in directory: /root/.cache/pip/wheels/c4/1a/79/20f55c470a50bb3702a8cb7c94d8ada15573538c7f4baebe2d
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
from apyori import apriori

In [ ]:
min_sup = 0.1

frequentItemsets = list(apriori(survey_association['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.2112676056338028, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.2112676056338028, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.49657534246575347, lift=1.36144957408387), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.5792276964047935, lift=1.36144957408387)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.2248664400194269, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.2248664400194269, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.5285388127853882, lift=1.0860892370510122), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.4620758483033932, lift=1.0860892370510122)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.18552695483244294, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.18552695483244294, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.5086551264980027, lift=1.045230444570247), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.3812375249500998, lift=1.045230444570247)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.10830500242836329, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.10830500242836329, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.2545662100456621, lift=1.372125200219943), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.2969374167776298, lift=1.3205057044171484), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.22255489021956087, lift=1.0534264803725881), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.5126436781609196, lift=1.0534264803725883), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.4816414686825054, lift=1.3205057044171487), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.5837696335078534, lift=1.372125200219943)])

# before filter

In [ ]:
# Calculate list lengths using apply with len()
survey_association['list_length'] = survey_association['for_association'].apply(len)

In [ ]:
survey_association.rename(columns={'r1':'ความชอบอันดับ 1', 'r2':'ความชอบอันดับ 2',
                      'r3':'ความชอบอันดับ 3', 'r4':'ความชอบอันดับ 4',
                      'r5':'ความชอบอันดับ 5', 'rr1':'ระบุอื่นๆ'}, inplace=True)

In [ ]:
time_filter_survey_association = survey_association.copy()

# filter เวลา

ช่วงเวลา k 1-10

## ช่วงเวลาที่ 1

In [ ]:
t1 = time_filter_survey_association[(time_filter_survey_association['k1'] == 1) & (time_filter_survey_association['list_length'] > 0) ]

In [ ]:
t1

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
76,1,0,0,0,0,0,1,0,0,0,15,6,8,9,13,99,"[15, 6, 8, 9, 13, 99]","[15, 6, 8, 9, 13]",5
107,1,1,0,0,0,0,0,0,0,0,1,3,8,10,18,99,"[1, 3, 8, 10, 18, 99]","[1, 3, 8, 10, 18]",5
108,1,0,0,0,0,0,1,0,0,0,15,8,7,18,9,99,"[15, 8, 7, 18, 9, 99]","[15, 8, 7, 18, 9]",5
111,1,0,0,0,0,0,0,0,0,0,1,15,2,3,8,99,"[1, 15, 2, 3, 8, 99]","[1, 15, 2, 3, 8]",5
115,1,0,0,0,0,1,0,0,0,0,2,15,4,3,17,99,"[2, 15, 4, 3, 17, 99]","[2, 15, 4, 3, 17]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764,1,0,1,0,0,0,1,1,0,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
1774,1,1,0,0,0,0,1,0,0,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
1777,1,1,1,0,0,0,1,0,0,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
1798,1,0,0,0,1,0,1,0,0,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
1813,1,0,0,0,1,0,1,0,0,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1

In [ ]:
min_sup = 0.1

frequentItemsets = list(apriori(t1['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.21359223300970873, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.21359223300970873, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.4313725490196078, lift=1.1692466460268316), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.5789473684210525, lift=1.1692466460268316)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.22330097087378642, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.22330097087378642, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.45098039215686275, lift=0.9479791916766707), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.46938775510204084, lift=0.9479791916766707)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.22330097087378642, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.22330097087378642, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.6052631578947368, lift=1.2722878625134264), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.46938775510204084, lift=1.2722878625134264)])
yes
RelationRecord(items=frozenset({3, 4}), support=0.10679611650485436, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 4}), confidence=0.10679611650485436, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({4}), confidence=0.22448979591836732, lift=1.5414965986394558), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({3}), confidence=0.7333333333333334, lift=1.5414965986394558)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.1262135922330097, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.1262135922330097, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.2549019607843137, lift=1.1415174765558396), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.34210526315789475, lift=1.532036613272311), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.2653061224489796, lift=1.2421150278293136), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.5909090909090909, lift=1.2421150278293136), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.5652173913043478, lift=1.532036613272311), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.5652173913043478, lift=1.1415174765558396)])

##ช่วงเวลาที่2

In [ ]:
t2 = time_filter_survey_association[(time_filter_survey_association['k2'] == 1) & (time_filter_survey_association['list_length'] > 0) ]

In [ ]:
t2

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
0,0,1,0,0,0,1,0,0,0,0,3,15,10,8,4,99,"[3, 15, 10, 8, 4, 99]","[3, 15, 10, 8, 4]",5
1,0,1,0,0,0,1,1,0,0,0,2,3,4,8,10,99,"[2, 3, 4, 8, 10, 99]","[2, 3, 4, 8, 10]",5
2,0,1,0,0,0,1,1,0,0,0,7,5,3,1,4,99,"[7, 5, 3, 1, 4, 99]","[7, 5, 3, 1, 4]",5
3,0,1,0,0,1,1,0,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
4,0,1,0,1,0,1,1,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2042,0,1,0,0,0,0,1,1,0,0,15,3,99,99,99,99,"[15, 3, 99, 99, 99, 99]","[15, 3]",2
2045,0,1,0,0,0,0,1,1,0,0,3,99,99,99,99,99,"[3, 99, 99, 99, 99, 99]",[3],1
2046,0,1,0,0,0,0,0,1,0,0,3,2,4,7,6,99,"[3, 2, 4, 7, 6, 99]","[3, 2, 4, 7, 6]",5
2049,0,1,1,0,0,0,1,1,0,0,3,2,1,7,18,99,"[3, 2, 1, 7, 18, 99]","[3, 2, 1, 7, 18]",5
2055,0,1,1,1,1,0,0,1,0,0,3,2,99,99,99,99,"[3, 2, 99, 99, 99, 99]","[3, 2]",2

In [ ]:
min_sup = 0.1

frequentItemsets = list(apriori(t2['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.2701342281879195, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.2701342281879195, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.5570934256055364, lift=1.312362378106323), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.6363636363636364, lift=1.3123623781063227)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.2953020134228188, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.2953020134228188, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.6089965397923875, lift=0.9653243024368696), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.4680851063829788, lift=0.9653243024368697)])
yes
RelationRecord(items=frozenset({1, 4}), support=0.15436241610738255, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 4}), confidence=0.15436241610738255, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({4}), confidence=0.31833910034602075, lift=1.5300814823082933), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({1}), confidence=0.7419354838709677, lift=1.5300814823082933)])
yes
RelationRecord(items=frozenset({1, 15}), support=0.10906040268456375, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 15}), confidence=0.10906040268456375, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({15}), confidence=0.22491349480968859, lift=1.155590025056676), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({1}), confidence=0.5603448275862069, lift=1.1555900250566757)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.2651006711409396, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.2651006711409396, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.6245059288537549, lift=0.9899083340341435), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.42021276595744683, lift=0.9899083340341435)])
yes
RelationRecord(items=frozenset({2, 4}), support=0.11912751677852348, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 4}), confidence=0.11912751677852348, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({4}), confidence=0.28063241106719367, lift=1.348846104806834), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({2}), confidence=0.5725806451612903, lift=1.3488461048068339)])
yes
RelationRecord(items=frozenset({3, 4}), support=0.13926174496644295, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 4}), confidence=0.13926174496644295, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({4}), confidence=0.22074468085106383, lift=1.0609986273164036), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({3}), confidence=0.6693548387096774, lift=1.0609986273164036)])
yes
RelationRecord(items=frozenset({8, 3}), support=0.1325503355704698, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 3}), confidence=0.1325503355704698, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8}), confidence=0.21010638297872342, lift=0.9275807722616234), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({3}), confidence=0.5851851851851851, lift=0.9275807722616233)])
yes
RelationRecord(items=frozenset({3, 15}), support=0.1342281879194631, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 15}), confidence=0.1342281879194631, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({15}), confidence=0.2127659574468085, lift=1.0931768158473956), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({3}), confidence=0.6896551724137931, lift=1.0931768158473956)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.15771812080536912, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.15771812080536912, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.32525951557093424, lift=1.2269282992422583), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.37154150197628455, lift=1.258174631692418), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.25, lift=0.9254658385093166), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.5838509316770185, lift=0.9254658385093166), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.5340909090909091, lift=1.258174631692418), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.5949367088607594, lift=1.2269282992422583)])
yes
RelationRecord(items=frozenset({1, 3, 4}), support=0.1040268456375839, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3, 4}), confidence=0.1040268456375839, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3, 4}), confidence=0.21453287197231835, lift=1.5405011047650812), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 4}), confidence=0.1648936170212766, lift=1.0682238667900095), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({1, 3}), confidence=0.5, lift=1.6931818181818181), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({4}), confidence=0.35227272727272724, lift=1.693181818181818), OrderedStatistic(items_base=frozenset({1, 4}), items_add=frozenset({3}), confidence=0.6739130434782609, lift=1.0682238667900092), OrderedStatistic(items_base=frozenset({3, 4}), items_add=frozenset({1}), confidence=0.746987951807229, lift=1.5405011047650812)])

##ช่วงเวลาที่3

In [ ]:
t3 = time_filter_survey_association[(time_filter_survey_association['k3'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t3

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
84,0,0,1,0,0,0,0,1,0,0,8,7,6,1,12,99,"[8, 7, 6, 1, 12, 99]","[8, 7, 6, 1, 12]",5
219,0,1,1,1,0,0,0,0,0,0,3,2,14,15,17,99,"[3, 2, 14, 15, 17, 99]","[3, 2, 14, 15, 17]",5
220,0,1,1,0,0,0,0,0,0,0,3,9,11,12,15,99,"[3, 9, 11, 12, 15, 99]","[3, 9, 11, 12, 15]",5
236,0,1,1,0,0,0,1,0,0,0,15,13,14,9,3,99,"[15, 13, 14, 9, 3, 99]","[15, 13, 14, 9, 3]",5
240,0,0,1,0,0,0,1,0,0,0,18,15,3,2,5,99,"[18, 15, 3, 2, 5, 99]","[18, 15, 3, 2, 5]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2052,0,0,1,0,0,1,1,1,0,1,2,3,8,99,99,99,"[2, 3, 8, 99, 99, 99]","[2, 3, 8]",3
2053,0,0,1,0,0,1,1,0,0,0,3,7,99,99,99,99,"[3, 7, 99, 99, 99, 99]","[3, 7]",2
2054,0,0,1,0,0,0,1,0,0,0,3,15,18,99,99,99,"[3, 15, 18, 99, 99, 99]","[3, 15, 18]",3
2055,0,1,1,1,1,0,0,1,0,0,3,2,99,99,99,99,"[3, 2, 99, 99, 99, 99]","[3, 2]",2
2057,0,0,1,0,0,1,1,1,0,0,3,99,99,99,99,99,"[3, 99, 99, 99, 99, 99]",[3],1

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t3['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.1650485436893204, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.1650485436893204, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.47887323943661975, lift=1.2178751521474527), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.4197530864197531, lift=1.2178751521474527)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.11650485436893204, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.11650485436893204, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.3380281690140845, lift=0.676056338028169), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.23300970873786409, lift=0.676056338028169)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.17475728155339806, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.17475728155339806, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.4444444444444445, lift=0.888888888888889), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.34951456310679613, lift=0.888888888888889)])
yes
RelationRecord(items=frozenset({3, 15}), support=0.10194174757281553, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 15}), confidence=0.10194174757281553, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({15}), confidence=0.20388349514563106, lift=0.9545454545454546), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({3}), confidence=0.4772727272727273, lift=0.9545454545454546)])

##ช่วงเวลาที่ 4

In [ ]:
t4 = time_filter_survey_association[(time_filter_survey_association['k4'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t4

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
4,0,1,0,1,0,1,1,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
34,0,1,0,1,0,1,1,0,0,0,1,4,3,2,15,99,"[1, 4, 3, 2, 15, 99]","[1, 4, 3, 2, 15]",5
35,0,1,0,1,0,1,1,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
36,0,1,0,1,0,1,1,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
37,0,1,0,1,0,1,1,0,0,0,3,1,2,7,15,99,"[3, 1, 2, 7, 15, 99]","[3, 1, 2, 7, 15]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1928,0,0,0,1,0,1,0,0,0,0,6,7,10,1,99,99,"[6, 7, 10, 1, 99, 99]","[6, 7, 10, 1]",4
2014,0,1,0,1,0,0,0,0,0,0,3,1,99,99,99,99,"[3, 1, 99, 99, 99, 99]","[3, 1]",2
2017,0,0,1,1,0,1,1,1,0,0,7,3,99,99,99,99,"[7, 3, 99, 99, 99, 99]","[7, 3]",2
2036,0,0,1,1,0,0,1,1,0,0,8,10,99,99,99,99,"[8, 10, 99, 99, 99, 99]","[8, 10]",2
2055,0,1,1,1,1,0,0,1,0,0,3,2,99,99,99,99,"[3, 2, 99, 99, 99, 99]","[3, 2]",2

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t4['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.2727272727272727, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.2727272727272727, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.6, lift=1.3014084507042254), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.5915492957746479, lift=1.3014084507042254)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.22727272727272727, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.22727272727272727, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.5, lift=0.9565217391304348), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.43478260869565216, lift=0.9565217391304348)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.23376623376623376, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.23376623376623376, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.5070422535211268, lift=0.969993876301286), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.4472049689440994, lift=0.969993876301286)])
yes
RelationRecord(items=frozenset({3, 15}), support=0.11363636363636363, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 15}), confidence=0.11363636363636363, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({15}), confidence=0.21739130434782608, lift=1.097647897362794), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({3}), confidence=0.5737704918032787, lift=1.097647897362794)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.1331168831168831, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.1331168831168831, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.2928571428571428, lift=1.2527777777777775), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.2887323943661972, lift=1.2704225352112677), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.2546583850931677, lift=0.9337474120082816), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.4880952380952381, lift=0.9337474120082816), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.5857142857142856, lift=1.2704225352112675), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.5694444444444444, lift=1.2527777777777778)])

##ช่วงเวลาที่ 5

In [ ]:
t5 = time_filter_survey_association[(time_filter_survey_association['k5'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t5

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
3,0,1,0,0,1,1,0,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
69,0,1,0,0,1,1,1,0,0,0,3,1,8,6,5,99,"[3, 1, 8, 6, 5, 99]","[3, 1, 8, 6, 5]",5
83,0,0,0,0,1,0,0,1,0,0,1,12,3,4,15,99,"[1, 12, 3, 4, 15, 99]","[1, 12, 3, 4, 15]",5
87,0,0,0,0,1,0,0,1,0,0,7,6,13,99,99,99,"[7, 6, 13, 99, 99, 99]","[7, 6, 13]",3
114,0,1,0,0,1,0,0,0,0,0,1,7,10,15,8,99,"[1, 7, 10, 15, 8, 99]","[1, 7, 10, 15, 8]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,0,0,1,0,1,1,1,1,0,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
1941,0,0,1,0,1,1,1,1,0,0,1,3,99,99,99,99,"[1, 3, 99, 99, 99, 99]","[1, 3]",2
1987,0,0,0,0,1,1,1,1,0,0,3,2,99,99,99,99,"[3, 2, 99, 99, 99, 99]","[3, 2]",2
2051,0,0,0,0,1,0,1,0,0,0,1,8,6,99,99,99,"[1, 8, 6, 99, 99, 99]","[1, 8, 6]",3
2055,0,1,1,1,1,0,0,1,0,0,3,2,99,99,99,99,"[3, 2, 99, 99, 99, 99]","[3, 2]",2

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t5['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.13513513513513514, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.13513513513513514, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.4210526315789474, lift=1.1029343269678622), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.3539823008849558, lift=1.1029343269678622)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.13175675675675674, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.13175675675675674, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.41052631578947363, lift=0.8557449962935507), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.27464788732394363, lift=0.8557449962935507)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.13851351351351351, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.13851351351351351, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.36283185840707965, lift=0.75632556400349), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.2887323943661972, lift=0.75632556400349)])

##ช่วงเวลาที่ 6

In [ ]:
t6 = time_filter_survey_association[(time_filter_survey_association['k6'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t6

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
0,0,1,0,0,0,1,0,0,0,0,3,15,10,8,4,99,"[3, 15, 10, 8, 4, 99]","[3, 15, 10, 8, 4]",5
1,0,1,0,0,0,1,1,0,0,0,2,3,4,8,10,99,"[2, 3, 4, 8, 10, 99]","[2, 3, 4, 8, 10]",5
2,0,1,0,0,0,1,1,0,0,0,7,5,3,1,4,99,"[7, 5, 3, 1, 4, 99]","[7, 5, 3, 1, 4]",5
3,0,1,0,0,1,1,0,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
4,0,1,0,1,0,1,1,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2052,0,0,1,0,0,1,1,1,0,1,2,3,8,99,99,99,"[2, 3, 8, 99, 99, 99]","[2, 3, 8]",3
2053,0,0,1,0,0,1,1,0,0,0,3,7,99,99,99,99,"[3, 7, 99, 99, 99, 99]","[3, 7]",2
2056,0,0,0,0,0,1,1,0,0,0,3,15,1,18,2,99,"[3, 15, 1, 18, 2, 99]","[3, 15, 1, 18, 2]",5
2057,0,0,1,0,0,1,1,1,0,0,3,99,99,99,99,99,"[3, 99, 99, 99, 99, 99]",[3],1
2058,0,0,0,0,0,1,1,1,0,0,2,15,18,19,7,99,"[2, 15, 18, 19, 7, 99]","[2, 15, 18, 19, 7]",5

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t6['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.24537037037037038, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.24537037037037038, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.53, lift=1.1505527638190955), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.5326633165829145, lift=1.1505527638190953)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.2800925925925926, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.2800925925925926, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.6050000000000001, lift=1.2044239631336409), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.5576036866359448, lift=1.2044239631336409)])
yes
RelationRecord(items=frozenset({1, 4}), support=0.1597222222222222, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 4}), confidence=0.1597222222222222, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({4}), confidence=0.345, lift=1.4611764705882353), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({1}), confidence=0.676470588235294, lift=1.461176470588235)])
yes
RelationRecord(items=frozenset({8, 1}), support=0.13425925925925927, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 1}), confidence=0.13425925925925927, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({8}), confidence=0.29000000000000004, lift=1.0527731092436976), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({1}), confidence=0.4873949579831933, lift=1.0527731092436976)])
yes
RelationRecord(items=frozenset({1, 15}), support=0.10185185185185185, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 15}), confidence=0.10185185185185185, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({15}), confidence=0.21999999999999997, lift=1.1181176470588232), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({1}), confidence=0.5176470588235293, lift=1.1181176470588234)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.21064814814814814, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.21064814814814814, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.457286432160804, lift=0.9103582428270385), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.41935483870967744, lift=0.9103582428270385)])
yes
RelationRecord(items=frozenset({2, 4}), support=0.14351851851851852, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 4}), confidence=0.14351851851851852, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({4}), confidence=0.31155778894472363, lift=1.319538870824712), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({2}), confidence=0.607843137254902, lift=1.319538870824712)])
yes
RelationRecord(items=frozenset({8, 2}), support=0.11805555555555555, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 2}), confidence=0.11805555555555555, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({8}), confidence=0.2562814070351759, lift=0.9303661162957645), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({2}), confidence=0.42857142857142855, lift=0.9303661162957645)])
yes
RelationRecord(items=frozenset({3, 4}), support=0.14351851851851852, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 4}), confidence=0.14351851851851852, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({4}), confidence=0.28571428571428575, lift=1.2100840336134455), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({3}), confidence=0.607843137254902, lift=1.2100840336134455)])
yes
RelationRecord(items=frozenset({8, 3}), support=0.14814814814814814, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 3}), confidence=0.14814814814814814, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8}), confidence=0.29493087557603687, lift=1.0706734306625876), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({3}), confidence=0.5378151260504201, lift=1.0706734306625876)])
yes
RelationRecord(items=frozenset({3, 15}), support=0.1388888888888889, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 15}), confidence=0.1388888888888889, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({15}), confidence=0.2764976958525346, lift=1.4052588777446462), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({3}), confidence=0.7058823529411764, lift=1.4052588777446462)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.1527777777777778, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.1527777777777778, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.33, lift=1.5665934065934066), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.3316582914572865, lift=1.1841023298309732), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.3041474654377881, lift=1.2395443874445702), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.6226415094339623, lift=1.2395443874445704), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.5454545454545454, lift=1.184102329830973), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.7252747252747254, lift=1.5665934065934068)])
yes
RelationRecord(items=frozenset({1, 2, 4}), support=0.10416666666666667, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 4}), confidence=0.10416666666666667, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 4}), confidence=0.225, lift=1.567741935483871), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 4}), confidence=0.22613065326633167, lift=1.4157745247979028), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({1, 2}), confidence=0.44117647058823534, lift=1.798002219755827), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({4}), confidence=0.42452830188679247, lift=1.798002219755827), OrderedStatistic(items_base=frozenset({1, 4}), items_add=frozenset({2}), confidence=0.6521739130434784, lift=1.4157745247979028), OrderedStatistic(items_base=frozenset({2, 4}), items_add=frozenset({1}), confidence=0.7258064516129032, lift=1.567741935483871)])
yes
RelationRecord(items=frozenset({1, 3, 4}), support=0.1111111111111111, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3, 4}), confidence=0.1111111111111111, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3, 4}), confidence=0.24, lift=1.672258064516129), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 4}), confidence=0.22119815668202766, lift=1.3848928070526951), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({1, 3}), confidence=0.47058823529411764, lift=1.680116674769081), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({4}), confidence=0.396694214876033, lift=1.680116674769081), OrderedStatistic(items_base=frozenset({1, 4}), items_add=frozenset({3}), confidence=0.6956521739130435, lift=1.384892807052695), OrderedStatistic(items_base=frozenset({3, 4}), items_add=frozenset({1}), confidence=0.7741935483870968, lift=1.672258064516129)])

##ช่วงเวลาที่7

In [ ]:
t7 = time_filter_survey_association[(time_filter_survey_association['k7'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t7

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
1,0,1,0,0,0,1,1,0,0,0,2,3,4,8,10,99,"[2, 3, 4, 8, 10, 99]","[2, 3, 4, 8, 10]",5
2,0,1,0,0,0,1,1,0,0,0,7,5,3,1,4,99,"[7, 5, 3, 1, 4, 99]","[7, 5, 3, 1, 4]",5
4,0,1,0,1,0,1,1,0,0,0,1,3,2,4,15,99,"[1, 3, 2, 4, 15, 99]","[1, 3, 2, 4, 15]",5
5,0,1,0,0,0,1,1,0,0,0,1,3,2,5,15,99,"[1, 3, 2, 5, 15, 99]","[1, 3, 2, 5, 15]",5
6,0,1,0,0,0,1,1,0,0,0,1,3,2,4,8,99,"[1, 3, 2, 4, 8, 99]","[1, 3, 2, 4, 8]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2053,0,0,1,0,0,1,1,0,0,0,3,7,99,99,99,99,"[3, 7, 99, 99, 99, 99]","[3, 7]",2
2054,0,0,1,0,0,0,1,0,0,0,3,15,18,99,99,99,"[3, 15, 18, 99, 99, 99]","[3, 15, 18]",3
2056,0,0,0,0,0,1,1,0,0,0,3,15,1,18,2,99,"[3, 15, 1, 18, 2, 99]","[3, 15, 1, 18, 2]",5
2057,0,0,1,0,0,1,1,1,0,0,3,99,99,99,99,99,"[3, 99, 99, 99, 99, 99]",[3],1
2058,0,0,0,0,0,1,1,1,0,0,2,15,18,19,7,99,"[2, 15, 18, 19, 7, 99]","[2, 15, 18, 19, 7]",5

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t7['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.23039690222652467, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.23039690222652467, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.505307855626327, lift=1.1703655041748784), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.5336322869955157, lift=1.1703655041748784)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.23814133591481124, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.23814133591481124, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.5222929936305732, lift=0.9954403365689707), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.45387453874538747, lift=0.9954403365689709)])
yes
RelationRecord(items=frozenset({1, 4}), support=0.11132623426911907, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 4}), confidence=0.11132623426911907, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({4}), confidence=0.24416135881104034, lift=1.3000963074835292), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({1}), confidence=0.5927835051546392, lift=1.3000963074835292)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.20038722168441434, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.20038722168441434, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.46412556053811665, lift=0.8845787897340858), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.38191881918819187, lift=0.8845787897340857)])
yes
RelationRecord(items=frozenset({2, 4}), support=0.10067763794772508, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 4}), confidence=0.10067763794772508, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({4}), confidence=0.2331838565022422, lift=1.2416439369423515), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({2}), confidence=0.5360824742268042, lift=1.2416439369423515)])
yes
RelationRecord(items=frozenset({3, 4}), support=0.10067763794772508, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 4}), confidence=0.10067763794772508, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({4}), confidence=0.1918819188191882, lift=1.0217217636093887), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({3}), confidence=0.5360824742268042, lift=1.0217217636093887)])
yes
RelationRecord(items=frozenset({8, 3}), support=0.10842207163601161, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 3}), confidence=0.10842207163601161, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8}), confidence=0.20664206642066418, lift=0.932145216648673), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({3}), confidence=0.4890829694323144, lift=0.932145216648673)])
yes
RelationRecord(items=frozenset({3, 15}), support=0.11616650532429816, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 15}), confidence=0.11616650532429816, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({15}), confidence=0.22140221402214022, lift=1.2635828015738721), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({3}), confidence=0.6629834254143646, lift=1.263582801573872)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.10842207163601161, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.10842207163601161, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.23779193205944799, lift=1.1866621537072934), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.25112107623318386, lift=1.0545043567027599), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.20664206642066418, lift=0.8968960277838072), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.47058823529411764, lift=0.8968960277838072), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.45528455284552843, lift=1.0545043567027599), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.5410628019323671, lift=1.1866621537072934)])

##ช่วงเวลาที่ 8

In [ ]:
t8 = time_filter_survey_association[(time_filter_survey_association['k8'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t8

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
27,0,1,0,0,0,1,1,1,0,0,1,15,4,3,2,99,"[1, 15, 4, 3, 2, 99]","[1, 15, 4, 3, 2]",5
78,0,0,0,0,0,1,0,1,0,0,8,7,6,12,1,99,"[8, 7, 6, 12, 1, 99]","[8, 7, 6, 12, 1]",5
80,0,0,0,0,0,1,0,1,0,0,12,8,7,6,1,99,"[12, 8, 7, 6, 1, 99]","[12, 8, 7, 6, 1]",5
81,0,0,0,0,0,0,0,1,0,0,1,2,3,12,10,99,"[1, 2, 3, 12, 10, 99]","[1, 2, 3, 12, 10]",5
83,0,0,0,0,1,0,0,1,0,0,1,12,3,4,15,99,"[1, 12, 3, 4, 15, 99]","[1, 12, 3, 4, 15]",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2050,0,0,0,0,0,1,1,1,0,0,1,8,6,99,99,99,"[1, 8, 6, 99, 99, 99]","[1, 8, 6]",3
2052,0,0,1,0,0,1,1,1,0,1,2,3,8,99,99,99,"[2, 3, 8, 99, 99, 99]","[2, 3, 8]",3
2055,0,1,1,1,1,0,0,1,0,0,3,2,99,99,99,99,"[3, 2, 99, 99, 99, 99]","[3, 2]",2
2057,0,0,1,0,0,1,1,1,0,0,3,99,99,99,99,99,"[3, 99, 99, 99, 99, 99]",[3],1
2058,0,0,0,0,0,1,1,1,0,0,2,15,18,19,7,99,"[2, 15, 18, 19, 7, 99]","[2, 15, 18, 19, 7]",5

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t8['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.23157894736842105, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.23157894736842105, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.5445544554455446, lift=1.2143820015804399), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.5164319248826291, lift=1.2143820015804399)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.2168421052631579, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.2168421052631579, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.5099009900990099, lift=0.9071272295768902), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.3857677902621722, lift=0.9071272295768902)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.22526315789473683, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.22526315789473683, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.5023474178403756, lift=0.8936892264950502), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.40074906367041196, lift=0.8936892264950501)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.10736842105263159, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.10736842105263159, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.2524752475247525, lift=1.1208013324696957), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.23943661971830987, lift=1.1041980035553125), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.19101123595505617, lift=0.8248212461695608), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.4636363636363637, lift=0.8248212461695608), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.4951456310679612, lift=1.1041980035553125), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.47663551401869164, lift=1.1208013324696957)])

##ช่วงเวลาที่ 9

In [ ]:
t9 = time_filter_survey_association[(time_filter_survey_association['k9'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t9

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
186,0,0,0,0,0,0,0,1,1,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
450,0,0,0,0,0,0,0,0,1,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
1036,0,0,1,0,1,0,1,1,1,0,3,7,99,99,99,99,"[3, 7, 99, 99, 99, 99]","[3, 7]",2
1258,0,0,0,0,0,0,0,1,1,0,14,15,16,99,99,99,"[14, 15, 16, 99, 99, 99]","[14, 15, 16]",3
1399,0,0,0,0,0,0,1,1,1,0,2,3,99,99,99,99,"[2, 3, 99, 99, 99, 99]","[2, 3]",2
1408,0,0,0,0,0,0,1,1,1,1,4,2,13,17,5,99,"[4, 2, 13, 17, 5, 99]","[4, 2, 13, 17, 5]",5
1444,0,0,0,0,0,0,1,1,1,0,3,15,99,99,99,99,"[3, 15, 99, 99, 99, 99]","[3, 15]",2
1475,0,0,0,0,0,0,1,1,1,0,3,8,1,99,99,99,"[3, 8, 1, 99, 99, 99]","[3, 8, 1]",3
1495,0,0,0,0,0,1,0,0,1,0,3,1,2,5,99,99,"[3, 1, 2, 5, 99, 99]","[3, 1, 2, 5]",4
1518,0,0,0,0,0,1,1,1,1,0,3,4,15,99,99,99,"[3, 4, 15, 99, 99, 99]","[3, 4, 15]",3
1588,0,0,0,0,0,1,1,1,1,0,11,2,99,99,99,99,"[11, 2, 99, 99, 99, 99]","[11, 2]",2
1914,0,0,0,0,0,0,0,0,1,0,8,15,10,18,1,99,"[8, 15, 10, 18, 1, 99]","[8, 15, 10, 18, 1]",5
1947,0,0,0,0,0,0,1,1,1,0,1,99,99,99,99,99,"[1, 99, 99, 99, 99, 99]",[1],1
2026,0,0,1,0,0,0,0,1,1,1,3,7,4,8,2,99,"[3, 7, 4, 8, 2, 99]","[3, 7, 4, 8, 2]",5
2031,0,0,1,0,0,0,1,1,1,0,3,7,5,8,2,99,"[3, 7, 5, 8, 2, 99]","[3, 7, 5, 8, 2]",5

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t9['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 3}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.3333333333333333, lift=0.625), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.25, lift=0.625)])
yes
RelationRecord(items=frozenset({8, 1}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 1}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({8}), confidence=0.3333333333333333, lift=1.25), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({1}), confidence=0.5, lift=1.25)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.26666666666666666, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.26666666666666666, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.6666666666666666, lift=1.25), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.5, lift=1.25)])
yes
RelationRecord(items=frozenset({2, 4}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 4}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({4}), confidence=0.3333333333333333, lift=1.6666666666666665), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({2}), confidence=0.6666666666666666, lift=1.6666666666666665)])
yes
RelationRecord(items=frozenset({2, 5}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 5}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({5}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({5}), items_add=frozenset({2}), confidence=1.0, lift=2.5)])
yes
RelationRecord(items=frozenset({2, 7}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 7}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({7}), confidence=0.3333333333333333, lift=1.6666666666666665), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({2}), confidence=0.6666666666666666, lift=1.6666666666666665)])
yes
RelationRecord(items=frozenset({8, 2}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 2}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({8}), confidence=0.3333333333333333, lift=1.25), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({2}), confidence=0.5, lift=1.25)])
yes
RelationRecord(items=frozenset({3, 4}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 4}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({4}), confidence=0.25, lift=1.25), OrderedStatistic(items_base=frozenset({4}), items_add=frozenset({3}), confidence=0.6666666666666666, lift=1.25)])
yes
RelationRecord(items=frozenset({3, 5}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 5}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({5}), confidence=0.25, lift=1.25), OrderedStatistic(items_base=frozenset({5}), items_add=frozenset({3}), confidence=0.6666666666666666, lift=1.25)])
yes
RelationRecord(items=frozenset({3, 7}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 7}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({7}), confidence=0.375, lift=1.875), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({3}), confidence=1.0, lift=1.875)])
yes
RelationRecord(items=frozenset({8, 3}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 3}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8}), confidence=0.375, lift=1.40625), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({3}), confidence=0.75, lift=1.40625)])
yes
RelationRecord(items=frozenset({3, 15}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 15}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({15}), confidence=0.25, lift=0.9375), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({3}), confidence=0.5, lift=0.9375)])
yes
RelationRecord(items=frozenset({8, 7}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 7}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({8}), confidence=0.6666666666666666, lift=2.5), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({7}), confidence=0.5, lift=2.5)])
yes
RelationRecord(items=frozenset({2, 3, 5}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3, 5}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3, 5}), confidence=0.3333333333333333, lift=2.5), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2, 5}), confidence=0.25, lift=1.25), OrderedStatistic(items_base=frozenset({5}), items_add=frozenset({2, 3}), confidence=0.6666666666666666, lift=2.5), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({5}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({2, 5}), items_add=frozenset({3}), confidence=0.6666666666666666, lift=1.25), OrderedStatistic(items_base=frozenset({3, 5}), items_add=frozenset({2}), confidence=1.0, lift=2.5)])
yes
RelationRecord(items=frozenset({2, 3, 7}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3, 7}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3, 7}), confidence=0.3333333333333333, lift=1.6666666666666665), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2, 7}), confidence=0.25, lift=1.875), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({2, 3}), confidence=0.6666666666666666, lift=2.5), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({7}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({2, 7}), items_add=frozenset({3}), confidence=1.0, lift=1.875), OrderedStatistic(items_base=frozenset({3, 7}), items_add=frozenset({2}), confidence=0.6666666666666666, lift=1.6666666666666665)])
yes
RelationRecord(items=frozenset({8, 2, 3}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 2, 3}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({8, 3}), confidence=0.3333333333333333, lift=1.6666666666666665), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8, 2}), confidence=0.25, lift=1.875), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({2, 3}), confidence=0.5, lift=1.875), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({8}), confidence=0.5, lift=1.875), OrderedStatistic(items_base=frozenset({8, 2}), items_add=frozenset({3}), confidence=1.0, lift=1.875), OrderedStatistic(items_base=frozenset({8, 3}), items_add=frozenset({2}), confidence=0.6666666666666666, lift=1.6666666666666665)])
yes
RelationRecord(items=frozenset({8, 2, 7}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 2, 7}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({8, 7}), confidence=0.3333333333333333, lift=2.5), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({8, 2}), confidence=0.6666666666666666, lift=5.0), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({2, 7}), confidence=0.5, lift=3.75), OrderedStatistic(items_base=frozenset({2, 7}), items_add=frozenset({8}), confidence=1.0, lift=3.75), OrderedStatistic(items_base=frozenset({8, 2}), items_add=frozenset({7}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({8, 7}), items_add=frozenset({2}), confidence=1.0, lift=2.5)])
yes
RelationRecord(items=frozenset({8, 3, 7}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 3, 7}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8, 7}), confidence=0.25, lift=1.875), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({8, 3}), confidence=0.6666666666666666, lift=3.333333333333333), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({3, 7}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({3, 7}), items_add=frozenset({8}), confidence=0.6666666666666666, lift=2.5), OrderedStatistic(items_base=frozenset({8, 3}), items_add=frozenset({7}), confidence=0.6666666666666666, lift=3.333333333333333), OrderedStatistic(items_base=frozenset({8, 7}), items_add=frozenset({3}), confidence=1.0, lift=1.875)])
yes
RelationRecord(items=frozenset({8, 2, 3, 7}), support=0.13333333333333333, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({8, 2, 3, 7}), confidence=0.13333333333333333, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({8, 3, 7}), confidence=0.3333333333333333, lift=2.5), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({8, 2, 7}), confidence=0.25, lift=1.875), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({8, 2, 3}), confidence=0.6666666666666666, lift=5.0), OrderedStatistic(items_base=frozenset({8}), items_add=frozenset({2, 3, 7}), confidence=0.5, lift=3.75), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({8, 7}), confidence=0.5, lift=3.75), OrderedStatistic(items_base=frozenset({2, 7}), items_add=frozenset({8, 3}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({8, 2}), items_add=frozenset({3, 7}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({3, 7}), items_add=frozenset({8, 2}), confidence=0.6666666666666666, lift=5.0), OrderedStatistic(items_base=frozenset({8, 3}), items_add=frozenset({2, 7}), confidence=0.6666666666666666, lift=5.0), OrderedStatistic(items_base=frozenset({8, 7}), items_add=frozenset({2, 3}), confidence=1.0, lift=3.75), OrderedStatistic(items_base=frozenset({2, 3, 7}), items_add=frozenset({8}), confidence=1.0, lift=3.75), OrderedStatistic(items_base=frozenset({8, 2, 3}), items_add=frozenset({7}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({8, 2, 7}), items_add=frozenset({3}), confidence=1.0, lift=1.875), OrderedStatistic(items_base=frozenset({8, 3, 7}), items_add=frozenset({2}), confidence=1.0, lift=2.5)])

##ช่วงเวลาที่ 10

In [ ]:
t10 = time_filter_survey_association[(time_filter_survey_association['k10'] == 1) & (time_filter_survey_association['list_length'] > 0) ]
t10

,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,ความชอบอันดับ 1,ความชอบอันดับ 2,ความชอบอันดับ 3,ความชอบอันดับ 4,ความชอบอันดับ 5,ระบุอื่นๆ,new_column,for_association,list_length
53,0,1,0,0,0,1,0,0,0,1,3,4,1,6,8,99,"[3, 4, 1, 6, 8, 99]","[3, 4, 1, 6, 8]",5
73,0,0,0,0,0,0,0,0,0,1,1,6,4,10,14,99,"[1, 6, 4, 10, 14, 99]","[1, 6, 4, 10, 14]",5
79,0,0,0,0,0,0,0,0,0,1,8,7,6,12,1,99,"[8, 7, 6, 12, 1, 99]","[8, 7, 6, 12, 1]",5
85,0,0,0,0,0,0,0,0,0,1,1,7,18,5,3,99,"[1, 7, 18, 5, 3, 99]","[1, 7, 18, 5, 3]",5
91,0,0,0,0,0,0,0,0,0,1,3,10,2,7,99,99,"[3, 10, 2, 7, 99, 99]","[3, 10, 2, 7]",4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821,0,0,0,0,0,0,0,0,0,1,7,99,99,99,99,99,"[7, 99, 99, 99, 99, 99]",[7],1
1822,0,0,0,0,0,0,0,0,0,1,7,99,99,99,99,99,"[7, 99, 99, 99, 99, 99]",[7],1
1994,0,0,0,0,0,0,0,0,0,1,2,3,4,1,7,99,"[2, 3, 4, 1, 7, 99]","[2, 3, 4, 1, 7]",5
2026,0,0,1,0,0,0,0,1,1,1,3,7,4,8,2,99,"[3, 7, 4, 8, 2, 99]","[3, 7, 4, 8, 2]",5
2052,0,0,1,0,0,1,1,1,0,1,2,3,8,99,99,99,"[2, 3, 8, 99, 99, 99]","[2, 3, 8]",3

In [ ]:
min_sup = 0.1
frequentItemsets = list(apriori(t10['for_association'],min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({1, 2}), support=0.22641509433962265, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2}), confidence=0.22641509433962265, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2}), confidence=0.4472049689440994, lift=1.3806910691672196), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1}), confidence=0.6990291262135923, lift=1.3806910691672194)])
yes
RelationRecord(items=frozenset({1, 3}), support=0.24213836477987422, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 3}), confidence=0.24213836477987422, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({3}), confidence=0.4782608695652174, lift=1.1975350907223554), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1}), confidence=0.6062992125984251, lift=1.1975350907223552)])
yes
RelationRecord(items=frozenset({1, 7}), support=0.11949685534591195, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 7}), confidence=0.11949685534591195, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({7}), confidence=0.2360248447204969, lift=0.9622551361681797), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({1}), confidence=0.48717948717948717, lift=0.9622551361681796)])
yes
RelationRecord(items=frozenset({1, 10}), support=0.10062893081761007, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 10}), confidence=0.10062893081761007, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({10}), confidence=0.1987577639751553, lift=1.5048802129547472), OrderedStatistic(items_base=frozenset({10}), items_add=frozenset({1}), confidence=0.761904761904762, lift=1.5048802129547472)])
yes
RelationRecord(items=frozenset({1, 15}), support=0.1320754716981132, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 15}), confidence=0.1320754716981132, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({15}), confidence=0.2608695652173913, lift=1.2762541806020067), OrderedStatistic(items_base=frozenset({15}), items_add=frozenset({1}), confidence=0.6461538461538461, lift=1.2762541806020065)])
yes
RelationRecord(items=frozenset({2, 3}), support=0.16352201257861634, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({2, 3}), confidence=0.16352201257861634, lift=1.0), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({3}), confidence=0.5048543689320388, lift=1.2641235379558138), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({2}), confidence=0.40944881889763773, lift=1.2641235379558136)])
yes
RelationRecord(items=frozenset({3, 7}), support=0.11006289308176101, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({3, 7}), confidence=0.11006289308176101, lift=1.0), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({7}), confidence=0.2755905511811024, lift=1.1235614778921865), OrderedStatistic(items_base=frozenset({7}), items_add=frozenset({3}), confidence=0.44871794871794873, lift=1.1235614778921865)])
yes
RelationRecord(items=frozenset({1, 2, 3}), support=0.11635220125786164, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({1, 2, 3}), confidence=0.11635220125786164, lift=1.0), OrderedStatistic(items_base=frozenset({1}), items_add=frozenset({2, 3}), confidence=0.2298136645962733, lift=1.4053989488772098), OrderedStatistic(items_base=frozenset({2}), items_add=frozenset({1, 3}), confidence=0.3592233009708738, lift=1.4835455806329594), OrderedStatistic(items_base=frozenset({3}), items_add=frozenset({1, 2}), confidence=0.29133858267716534, lift=1.2867454068241468), OrderedStatistic(items_base=frozenset({1, 2}), items_add=frozenset({3}), confidence=0.5138888888888888, lift=1.2867454068241468), OrderedStatistic(items_base=frozenset({1, 3}), items_add=frozenset({2}), confidence=0.4805194805194805, lift=1.4835455806329594), OrderedStatistic(items_base=frozenset({2, 3}), items_add=frozenset({1}), confidence=0.7115384615384616, lift=1.4053989488772098)])